name: 'coverage'
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        permissions:
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
                with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}